#!/bin/bash

# export so that we can use it in subscripts.
export UMBASEPATH=`realpath $0 | xargs dirname`

# catch first arguments with $1
case "$1" in
    next)
        $UMBASEPATH/next.sh $2
        ;;
    last)
        $UMBASEPATH/last.sh
        ;;
    cat)
        # all args but first
        $UMBASEPATH/cat.sh "${@:2}"
        ;;
    rename)
        $UMBASEPATH/rename.sh $2 $3
        ;;
    tag)
        $UMBASEPATH/tag.sh $2
        ;;
    *)
        echo "usage: um (next|last|cat|rename|tag)"
        ;;
esac
