#!/bin/bash

# export so that we can use it in subscripts.
export UMBASEPATH=`realpath $0 | xargs dirname`

# catch first arguments with $1
case "$1" in
    next)
        $UMBASEPATH/bash/next/next.sh $2
        ;;
    last)
        $UMBASEPATH/bash/last/last.sh
        ;;
    cat)
        # all args but first
        $UMBASEPATH/bash/mdcat/mdcat.sh "${@:2}"
        ;;
    rename)
        $UMBASEPATH/bash/rename/rename.sh "${@:2}"
        ;;
    *)
        # else
        echo "usage: um (next|last|cat|rename)"
        ;;
esac
