#!/bin/bash

# catch first arguments with $1
case "$1" in
    next)
        NEXTFILE=`./bash/next/next.sh $2`
        emacsclient --eval "(progn (find-file \"$NEXTFILE\") (journal))"
        ;;
    last)
        ./bash/last/last.sh
        ;;
    cat)
        # all args but first
        ./bash/mdcat/mdcat.sh "${@:2}"
        ;;
    rename)
        ./bash/rename/rename.sh "${@:2}"
        ;;
    *)
        # else
        echo "usage: um (next|last|cat|rename)"
        ;;
esac
